name: Save Docker Image to Branch

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Docker image to pull'
        required: true
        default: 'nginx:latest'

jobs:
  save-image:
    runs-on: ubuntu-latest

    permissions:
      contents: write  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Pull Docker image
      run: docker pull ${{ github.event.inputs.docker_image }}

    - name: Save Docker image to tar file
      run: docker save -o image.tar ${{ github.event.inputs.docker_image }}

    - name: Set up Git LFS
      run: |
        git lfs install
        git lfs track "*.tar"

    - name: Set Git user
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: image.tar
        path: /
